config/routes.rb
Rails.application.routes.draw do
  resources :rafflrs
  root 'rafflrs#index'

  get 'new_user' => "users#new", :as => "new_user"
  resources :users

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  resources :sessions

  

end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
end

app/models/rafflr.rb
class Rafflr < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :username, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/rafflrs_controller.rb
class RafflrsController < ApplicationController
  def index
  end
  def create
    @raffle = Rafflr.new(rafflr_params)
    if @raffle.save
      # do something
      flash[:success] = "Welcome to Rafflr"
      redirect_to @raffle 
    end
  end

  def new
    @page_title = "New Raffle"
    @raffle = Rafflr.new
  end

  def show
    @raffle = Rafflr.find(params[:id])
    @raffle_players =@raffle.players.split(/\s+/)
    @raffle_winners = @raffle_players.shuffle.pop(@raffle.number_of_winners)
  end

  def run_raffle
  end

  private
    def rafflr_params
      params.require(:rafflr).permit( :players, :number_of_winners)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged In"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out"
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end
``

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "User Created!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rafflrs_helper.rb
module RafflrsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.haml
%footer{ :class => "footer" }
  %small
    %a{ :href => "" }
  %nav
    %ul
      %li= link_to "About", "#"

app/views/layouts/_header.haml
%header{ :class => "navbar navbar-fixed-top navbar-inverse" }
  .container
    = link_to "Rafflearn", root_path, id: "logo"
    %nav{ :class => "nav navbar-nav navbar-right"}
      %li= link_to "Home", root_path

app/views/layouts/application.haml
!!! Strict
%html
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1")
    %title= @title
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" 
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' 
    = csrf_meta_tags
  %body
    = render :partial => 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{ :class => ['alert', 'alert-' + message_type] } 
          %p= message
      = yield 
      = render :partial => 'layouts/footer'

app/views/rafflrs/create.html.haml
%p Do something here

app/views/rafflrs/index.html.haml
%h1 Welcome to the rafflr!
%h1= link_to 'Start', new_rafflr_path

app/views/rafflrs/new.html.haml
%h1 Who is going to win? 
.row
  .col-md-6.col-md-offset-3
    = form_for(@raffle) do |f|
      = render 'shared/error_messages'

      = f.label :players, class: "start_raffle"
      = f.text_area :players, class: "form-control"

      = f.label :number_of_winners, class: "start_raffle"
      = f.number_field :number_of_winners, class: "form-control"

      = f.submit "Submit", class: "btn btn-primary start_raffle"

app/views/rafflrs/show.haml
%h1 Players
%p= @raffle_players

app/views/shared/_error_messages.haml
- if @raffle.errors.any?
  #error_explanation
    .alert.alert-danger 
      %p The form contains #{pluralize(@raffle.errors.count, "error")}
    %ul
    - @raffle.errors.full_messages.each do |msg|
      %li= msg

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_for @user do |f| %>|
    <% if @user.errors.any? %>
        <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
                <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>

<% end %>